/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@interface RainDropAppDelegate : NSObject
{
    id *soundcloudController;
    id *loginController;
    id *mainWindowController;
    NSMenuItem *mainMenuPlayPauseItem;
    NSMenuItem *mainMenuDisconnectItem;
    NSMenuItem *dockPlayPauseItem;
    NSMenu *dockMenu;
    id localFavoritingEventMonitor;
}

@property(readonly) NSMenuItem *mainMenuDisconnectItem; // @synthesize mainMenuDisconnectItem;
@property(readonly) NSMenuItem *mainMenuPlayPauseItem; // @synthesize mainMenuPlayPauseItem;
@property(readonly) NSMenu *dockMenu; // @synthesize dockMenu;
@property(readonly) NSMenuItem *dockPlayPauseItem; // @synthesize dockPlayPauseItem;
@property(readonly) id *loginController; // @synthesize loginController;
@property(readonly) id *soundcloudController; // @synthesize soundcloudController;
@property(readonly) id *mainWindowController; // @synthesize mainWindowController;

- (void)registerDefaultSettings;
- (void)volumeDown:(id)arg1;
- (void)volumeUp:(id)arg1;
- (void)playPrevious:(id)arg1;
- (void)playNext:(id)arg1;
- (void)playPause:(id)arg1;
- (void)openFeedbackPage:(id)arg1;
- (void)openHelp:(id)arg1;
- (void)disconnect:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)playPauseStateDidChange:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (BOOL)applicationShouldHandleReopen:(id)arg1 hasVisibleWindows:(BOOL)arg2;
- (void)savePlaylists;
- (void)showFriendFinder:(id)arg1;
- (void)showDownloadManager:(id)arg1;
- (void)showMainWindow:(id)arg1;
- (void)launchMainWindow;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)dealloc;
- (id)init;

@end
